version: '3.3'
services:
    mock-api:
        volumes:
            - "./my-mock-api-folder:/app/mock-api:ro"
        environment:
            - SUBDOMAIN=custom-subdomain
            - URL_PATH=/api
        ports:
            - '3000:3000'
        container_name: mock-api
        image: andrebnassis/mock-api